### ISSUE TITLE
More Descriptive Errors for Failed Spot Launch

### ISSUE THREAD

**Issue by ChrisSuess** [ChrisSuess/Project-Xbow#33]
When requesting a spot instance that is unavailable xbow will timeout and give the following error:

```
Starting the scheduler node - this may take some time...
Scheduler ready, now starting workers. This may take some time...
Traceback (most recent call last):
  File "/home/akuzmanic/anaconda3/bin/xbow-create_cluster", line 164, in <module>
    user_data=user_data
  File "/home/akuzmanic/anaconda3/lib/python3.6/site-packages/xbow/pools.py", line 92, in create_spot_pool
    waiter.wait(Filters=filters)
  File "/home/akuzmanic/anaconda3/lib/python3.6/site-packages/botocore/waiter.py", line 53, in wait
    Waiter.wait(self, **kwargs)
  File "/home/akuzmanic/anaconda3/lib/python3.6/site-packages/botocore/waiter.py", line 329, in wait
    last_response=response
botocore.exceptions.WaiterError: Waiter SpotInstanceRequestFulfilled failed: Max attempts exceeded
```

Everything will be set up normally and the spot request will have been created but a more descriptive error message saying 'everything is okay and will run when available' would be very useful to the user.

**Comment by tonka-balonka** [comment]
Hey @ChrisSuess, IMHO this would really help. I was completely confused the first time I saw the error and thought sth went wrong in the process :slightly_smiling_face:
