### ISSUE TITLE
xbow-configure fails if .xbow already exists

### ISSUE THREAD

**Issue by CharlieLaughton** [ChrisSuess/Project-Xbow#7]
If you run xbow-configure and you already have a .xbow directory, it throws an error:
```
(py27) Charless-MacBook-Pro:~ pazcal$ xbow-configure
Xbow will create a hidden directory in your $HOME directory 
in which it will create the hosts configuration file. You will
need to edit this file with your cloud preferences for the 
cloud machines you wish to use. See documentation for more 
information on best cloud practices.
Traceback (most recent call last):
  File "/Users/pazcal/miniconda3/envs/py27/bin/xbow-configure", line 165, in <module>
    result3 = create_settings()
  File "/Users/pazcal/miniconda3/envs/py27/bin/xbow-configure", line 38, in create_settings
    os.mkdir(os.path.expanduser('~/.xbow'))
OSError: [Errno 17] File exists: '/Users/pazcal/.xbow'
```

**Comment by ChrisSuess** [comment]
`if not os.path.exists(os.path.expanduser('~/.xbow')):`

Original code was missing the expand user so wasn't treating ~ as $HOME. This has been fixed in the latest commit  b27ae8a 

I have tested on a few a machines and it has worked, does this work for you @CharlieLaughton ?
